services:
  db_prod:
    image: postgres
    restart: always
    # env_file:
    #   - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: STnIoySaq3BxmUIONrcs
      POSTGRES_DB: cesi-zen
    volumes:
      - data_prod:/var/lib/postgresql/data
    ports:
      - "21701:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cesizen_prod

  api_prod:
    image: ghcr.io/fadibouch/cesi-zen-api:latest
    restart: always
    # env_file:
    #   - .env
    environment:
      DATABASE_URL: postgresql://postgres:STnIoySaq3BxmUIONrcs@db_prod:5432/cesi-zen?schema=public
    ports:
      - "3001:3000"
    depends_on:
      db_prod:
        condition: service_healthy
    networks:
      - cesizen_prod

  web_prod:
    image: ghcr.io/fadibouch/cesi-zen-web:latest
    restart: always
    environment:
      - VITE_BASE_URL=http://44.212.98.79:3001
    ports:
      - "80:5173"
    networks:
      - cesizen_prod

networks:
  cesizen_prod:
volumes:
  data_prod:
