services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cesi-zen
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "21501:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cesizen

  api:
    build:
      context: ./api/.
      target: final
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:1234@db:5432/cesi-zen
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    command: ["npm", "run", "dev"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cesizen

  web:
    build:
      context: ./web/.
      target: final
    environment:
      - NODE_ENV=development
      - VITE_BASE_URL=http://localhost:3000
    ports:
      - "80:5173"
    volumes:
      - ./web:/app
    depends_on:
      - api
    networks:
      - cesizen

networks:
  cesizen:
volumes:
  data:
